### ISSUE TITLE
Refactor use of name, tmp, show triplet

### ISSUE THREAD

**Issue by abelsiqueira** [TulipaEnergy/TulipaIO.jl#31]
There are $2^3 = 8$ possibilities. Refactor so these are clear.
Possibly create a function to assist.

A possible implementation is using `Val`. E.g.,

```
function foo(::Val{true}, x)
  return x + 1
end

function foo(::Val{false}, x)
  return x - 1
end

function foo(x)
  if x > 0
    return foo(Val(true), x)
  else
    return foo(Val(false), x)
  end
end
```

**Comment by suvayu** [comment]
Some notes on behaviour, for a given source:

1. source is a file:

   | name      | tmp         | show   | remarks                          |
   |-----------|-------------|--------|----------------------------------|
   | non-empty | as provided | ignore | use `get_table` if you want a DF |
   | empty     | true        | ignore | table name: "t_<safe_filename>"  |
   | empty     | false->true | false  | ditto                            |
   | empty     | false       | true   | returns DF (for debugging)       |

2. source is another table: TBD since now the scope of TIO also
   includes API usage from TEM.
